# Generated by Django 5.0.6 on 2024-06-29 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_alter_measurement_sensor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='measurement_time',
            new_name='created_at',
        ),
    ]
